antioch/client/urls.py
# antioch
# Copyright (c) 1999-2018 Phil Christensen
#
#
# See LICENSE for details

from django.urls import path

from django.contrib.auth.views import LoginView
from .views import rest, comet, logout, client

app_name = "client"
urlpatterns = [
    path(r'login/', LoginView.as_view(template_name='client/login.html'), name="login"),
    path(r'rest/<slug:command>', rest, name='rest'),
    path(r'comet/', comet, name='comet'),
    path(r'logout/', logout, name='logout'),
    path(r'', client, name='client'),
]

antioch/urls.py
# antioch
# Copyright (c) 1999-2018 Phil Christensen
#
#
# See LICENSE for details

"""
Django URL routes.
"""

from django.urls import include, path

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path(r'', include('antioch.plugins.urls')),
    path(r'admin/', admin.site.urls),
    path(r'', include('antioch.client.urls')),
]

antioch/client/views.py
# antioch
# Copyright (c) 1999-2018 Phil Christensen
#
#
# See LICENSE for details

"""
Django client views.
"""

import os.path, time, logging

from django import template, shortcuts, http
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.middleware import csrf
from django.views.decorators.csrf import csrf_exempt

import json

from antioch import plugins, celery_config
from antioch.core import parser, tasks

log = logging.getLogger(__name__)

@login_required
def client(request):
    """
    Return the main client window.
    """
    return shortcuts.render(request, 'client/client.html', dict(
        title           = "antioch client",
        scripts         = [p.script_url for p in plugins.iterate() if p and p.script_url],
    ))

@login_required
def comet(request):
    """
    Check for messages for this user.
    """
    queue_id = '-'.join([settings.USER_QUEUE, str(request.user.avatar.id)])
    log.debug("checking for messages for %s" % queue_id)

    with celery_config.app.default_connection() as conn:
        from kombu import simple, Exchange, Queue
        exchange = Exchange('antioch',
            type            = 'direct',
            auto_delete     = False,
            durable         = True,
        )
        channel = conn.channel()
        unbound_queue = Queue(queue_id,
            exchange        = exchange,
            routing_key     = queue_id,
            auto_delete     = False,
            durable         = False,
            exclusive       = False,
        )
        queue = unbound_queue(channel)
        queue.declare()

        sq = simple.SimpleBuffer(channel, queue, no_ack=True)
        try:
            msg = sq.get(block=True, timeout=10)
            messages = [msg.body.decode()]
        except sq.Empty as e:
            messages = []
        sq.close()
    
    log.debug('returning to client: %s' % messages)
    return http.HttpResponse('[%s]' % ','.join(messages), content_type="application/json")

@login_required
@csrf_exempt
def rest(request, command):
    """
    Query the appserver and wait for a response.
    """
    kwargs = json.loads(request.read())

    task = getattr(tasks, command)
    result = task.delay(request.user.avatar.id, **kwargs)
    data = result.get(timeout=settings.JOB_TIMEOUT)
    response = json.dumps(data)

    return http.HttpResponse(response, content_type="application/json")

def logout(request):
    """
    Logout of antioch.
    """
    tasks.logout.delay(request.user.avatar.id)
    auth.logout(request)
    return shortcuts.redirect('client:client')

antioch/client/templates/client/client.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}
  <link rel="stylesheet/less" type="text/css" href="{% static 'client/css/client.less' %}" />
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">{{ request.user.avatar.name }}</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
              <li><a class="inventory-cmd">inventory</a></li>
              <li><a class="password-cmd">change password</a></li>
              {% if request.user.wizard %}
              <li><a href="/admin" target="_blank">administration</a></li>
              {% endif %}
              <li><a href="/logout">logout</a></li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
    <div id="observations">
    </div>
    <div id="command-line">
        <input type="text" id="connection" class="client-prompt" placeholder="What do you want to do?" />
    </div>
    <div id="actions">
    </div>
{% endblock %}

{% block footer %}
<script type="text/javascript" src="{% static 'common/js/libs/relative-date.js' %}"></script>
<script type="text/javascript" src="{% static 'client/js/client.js' %}"></script>
{% for script_url in scripts %}
<script type="text/javascript" src="{{ script_url }}"></script>
{% endfor %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#connection').antioch({
            listen: true,
            callback: function(){
                $('#connection').antioch('callRemote', 'parse', {sentence: 'look here'});
            },
            
            actions_selector: "#actions",
            
            players_wrapper_node: '<div class="players-list"></div>',
            players_list_node: '<ul></ul>',
            player_list_item_node: '<li class="btn btn-small"></li>',
            player_image_node: '<div class="player-image"></div>',
            player_image_template: "<img src=\"$content\" >",
            default_image_node: '<img src="{% static 'client/images/silhouette.png' %}" >',
            player_name_node: '<div class="player-name"></div>',
            player_mood_node: '<div class="player-mood"></div>',
            people_here_node: '<strong>people here:</strong>',
            
            contents_wrapper_node: '<div class="contents-list"></div>',
            contents_list_node: '<ul></ul>',
            content_list_item_node: '<li class="btn btn-small"></li>',
            contents_here_node: '<strong>obvious contents:</strong>',
            clear_both_node: '<br style="clear: both;"/>',
        });
        
        $('.inventory-cmd').click(function(){
            $('#connection').antioch('callRemote', 'parse', {sentence: 'look me'});
        });
        
        $('.description-cmd').click(function(){
            $('#connection').antioch('callRemote', 'parse', {sentence: 'edit description on me'});
        });
        
        $('.password-cmd').click(function(){
            $('#connection').antioch('callRemote', 'parse', {sentence: 'passwd'});
        });
        
        setInterval(function(){
            $('.keep-relative').each(function(){
                var dstr = $(this).find('.real-date').html();
                $(this).find('.relative-date').html(relativeDate(new Date(dstr)));
            });
        }, 10);
    });
</script>
{% endblock %}

antioch/client/templates/client/login.html
{% extends 'base.html' %}
{% load staticfiles widget_tweaks %}

{% block header %}
<link rel="stylesheet/less" type="text/css" href="{% static 'client/css/client-login.less' %}" />
{% endblock %}

{% block content_class %}col-xs-4{% endblock %}

{% block content %}

<form class="form-signin" role="form" method="post" action="{% url 'client:login' %}">
    {% csrf_token %}
  <h2 class="form-signin-heading">Please sign in to antioch</h2>
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    {% render_field form.username class="form-control" placeholder="Username" required="" autofocus="" %}
    {% render_field form.password class="form-control" placeholder="Password" required="" %}
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>

{% endblock %}