antioch/plugins/editors/urls.py
from django.urls import include, path

from antioch.plugins.editors import views

app_name = 'editors'

urlpatterns = [
    path(r'editor/object/<int:pk>', views.ObjectEditorFormView.as_view(), name='object_editor'),
    path(r'editor/property/<int:pk>', views.PropertyEditorFormView.as_view(), name='property_editor'),
    path(r'editor/verb/<int:pk>', views.VerbEditorFormView.as_view(), name='verb_editor'),
    path(r'editor/access/<slug:type>/<int:pk>', views.AccessEditorFormView.as_view(), name='access_editor'),
]

antioch/urls.py
# antioch
# Copyright (c) 1999-2018 Phil Christensen
#
#
# See LICENSE for details

"""
Django URL routes.
"""

from django.urls import include, path

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path(r'', include('antioch.plugins.urls')),
    path(r'admin/', admin.site.urls),
    path(r'', include('antioch.client.urls')),
]

antioch/core/models.py
# antioch
# Copyright (c) 1999-2018 Phil Christensen
#
#
# See LICENSE for details

from django.db import models

class Object(models.Model):
    class Meta:
        db_table = 'object'
    
    name = models.CharField(max_length=255)
    unique_name = models.BooleanField()
    owner = models.ForeignKey('self', related_name='+', null=True, on_delete=models.SET_NULL)
    location = models.ForeignKey('self', related_name='contents', null=True, on_delete=models.SET_NULL)
    parents = models.ManyToManyField('self', related_name='children', symmetrical=False, through='Relationship')
    observers = models.ManyToManyField('self', related_name='observing', symmetrical=False, through='Observation')
    
    def __unicode__(self):
        return "#%s (%s)" % (self.id, self.name)

class Relationship(models.Model):
    class Meta:
        db_table = 'object_relation'
    
    child = models.ForeignKey(Object, related_name='parent', on_delete=models.CASCADE)
    parent = models.ForeignKey(Object, related_name='child', on_delete=models.CASCADE)
    weight = models.IntegerField(default=0)

class Observation(models.Model):
    class Meta:
        db_table = 'object_observer'
    
    object = models.ForeignKey(Object, related_name='observer', on_delete=models.CASCADE)
    observer = models.ForeignKey(Object, related_name='object', on_delete=models.CASCADE)

class Alias(models.Model):
    class Meta:
        verbose_name_plural = 'aliases'
        db_table = 'object_alias'
    
    object = models.ForeignKey(Object, related_name='aliases', on_delete=models.CASCADE)
    alias = models.CharField(max_length=255)

class Verb(models.Model):
    class Meta:
        db_table = 'verb'
    
    code = models.TextField(blank=True, null=True)
    filename = models.CharField(max_length=255, blank=True, null=True)
    owner = models.ForeignKey(Object, related_name='+', null=True, on_delete=models.SET_NULL)
    origin = models.ForeignKey(Object, related_name='verbs', on_delete=models.CASCADE)
    ability = models.BooleanField()
    method = models.BooleanField()
    
    def __unicode__(self):
        return "%s {#%s on %s}" % (
            self.annotated(), self.id, self.origin
        )
    
    def annotated(self):
        ability_decoration = ['', '@'][self.ability]
        method_decoration = ['', '()'][self.method]
        verb_name = self.name()
        return ''.join([ability_decoration, verb_name, method_decoration])
    
    def name(self):
        return self.names.all()[0].name

class VerbName(models.Model):
    class Meta:
        db_table = 'verb_name'
    
    verb = models.ForeignKey(Verb, related_name='names', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    
    def __unicode__(self):
        return "%s {#%s on %s}" % (
            self.name, self.verb.id, self.verb.origin
        )


class Property(models.Model):
    class Meta:
        verbose_name_plural = 'properties'
        db_table = 'property'
    
    name = models.CharField(max_length=255)
    value = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=255, choices=[(x,x) for x in ('string', 'python', 'dynamic')])
    owner = models.ForeignKey(Object, related_name='+', null=True, on_delete=models.SET_NULL)
    origin = models.ForeignKey(Object, related_name='properties', on_delete=models.CASCADE)
    
    def __unicode__(self):
        return '%s {#%s on %s}' % (self.name, self.id, self.origin)

class Permission(models.Model):
    class Meta:
        db_table = 'permission'
    
    name = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.name

class Access(models.Model):
    class Meta:
        verbose_name_plural = 'access controls'
        db_table = 'access'
    
    object = models.ForeignKey(Object, related_name='acl', null=True, on_delete=models.CASCADE)
    verb = models.ForeignKey(Verb, related_name='acl', null=True, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, related_name='acl', null=True, on_delete=models.CASCADE)
    rule = models.CharField(max_length=5, choices=[(x,x) for x in ('allow', 'deny')])
    permission = models.ForeignKey(Permission, related_name='usage', on_delete=models.CASCADE)
    type = models.CharField(max_length=8, choices=[(x,x) for x in ('accessor', 'group')])
    accessor = models.ForeignKey(Object, related_name='rights', null=True, on_delete=models.CASCADE)
    group = models.CharField(max_length=8, null=True, choices=[(x,x) for x in ('everyone', 'owners', 'wizards')])
    weight = models.IntegerField(default=0)
    
    def actor(self):
        return self.accessor if self.type == 'accessor' else self.group
    
    def entity(self):
        if self.object:
            return 'self'
        elif self.verb:
            return ''.join([
                ['', '@'][self.verb.ability],
                self.verb.names.all()[:1][0].name,
                ['', '()'][self.verb.method],
            ])
        else:
            return self.property.name

    def origin(self):
        if self.object:
            return self.object 
        elif self.verb:
            return self.verb.origin
        else:
            return self.property.origin
    
    def __unicode__(self):
        try:
            return '%(rule)s %(actor)s %(permission)s on %(entity)s (%(weight)s)' % dict(
                rule        = self.rule,
                actor        = self.actor(),
                permission    = self.permission.name,
                entity        = self.entity(),
                weight        = self.weight,
            )
        except Exception as e:
            import traceback
            traceback.print_exc();
            return str(e)

class Player(models.Model):
    class Meta:
        db_table = 'player'
        app_label = 'core'
    
    def __unicode__(self):
        return self.email

    def is_authenticated(self):
        return True
    
    @property
    def is_active(self):
        return True
    
    @property
    def is_staff(self):
        return self.wizard
    
    @property
    def is_superuser(self):
        return self.wizard
    
    def has_module_perms(self, app):
        return True
    
    def has_perm(self, perm):
        return True
    
    avatar = models.ForeignKey(Object, null=True, on_delete=models.SET_NULL)
    session_id = models.CharField(max_length=255, null=True, blank=True)
    wizard = models.BooleanField(default=False)
    enabled = models.BooleanField(default=True)
    crypt = models.CharField(max_length=255, null=True, blank=True)
    last_login = models.DateTimeField(null=True)
    last_logout = models.DateTimeField(null=True)

class Task(models.Model):
    class Meta:
        db_table = 'task'
    
    user = models.ForeignKey(Object, related_name='tasks', on_delete=models.CASCADE)
    origin = models.ForeignKey(Object, related_name='+', on_delete=models.CASCADE)
    verb_name = models.CharField(max_length=255)
    args = models.TextField()
    kwargs = models.TextField()
    created = models.DateTimeField()
    delay = models.IntegerField()
    killed = models.BooleanField(default=False)
    error = models.CharField(max_length=255, blank=True, null=True)
    trace = models.TextField(blank=True, null=True)

antioch/plugins/editors/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import BaseModelFormSet

# import autocomplete_light

from antioch.core import models
from antioch.plugins.editors import tasks

# class AuthenticatedModelForm(autocomplete_light.ModelForm):
class AuthenticatedModelForm(forms.ModelForm):
    def __init__(self, user_id=None, *args, **kwargs):
        super(AuthenticatedModelForm, self).__init__(*args, **kwargs)
        self.user_id = user_id

class ObjectForm(AuthenticatedModelForm):
    class Meta:
        model = models.Object
        exclude = ('observers',)
        autocomplete_fields = ('owner', 'location', 'parents')
    
    def clean_location(self):
        value = self.cleaned_data['location']
        return value.id if value else None
    
    def clean_owner(self):
        value = self.cleaned_data['owner']
        return value.id if value else None
    
    def clean_parents(self):
        value = self.cleaned_data['parents']
        return [x.id for x in value or []]
    
    def _post_clean(self):
        pass
    
    def save(self, force_insert=False, force_update=False, commit=True):
        tasks.modifyobject.delay(
            user_id        = self.user_id,
            object        = self.instance.id,
            name        = self.cleaned_data['name'],
            location    = self.cleaned_data['location'],
            owner        = self.cleaned_data['owner'],
            parents        = self.cleaned_data['parents']
        ).get(timeout=5)
        return self

class PropertyForm(AuthenticatedModelForm):
    class Meta:
        model = models.Property
        exclude = ('origin',)
        autocomplete_fields = ('owner',)
    
    value = forms.CharField(widget=widgets.HiddenInput)
    
    def clean_owner(self):
        value = self.cleaned_data['owner']
        return value.id if value else None
    
    def _post_clean(self):
        pass
    
    def save(self, force_insert=False, force_update=False, commit=True):
        tasks.modifyproperty.delay(
            user_id        = self.user_id,
            object        = self.instance.origin.id,
            property_id = self.instance.id,
            name        = self.cleaned_data['name'],
            value        = self.cleaned_data['value'],
            type        = self.cleaned_data['type'],
            owner        = self.cleaned_data['owner'],
        ).get(timeout=5)
        return self

class VerbForm(AuthenticatedModelForm):
    class Meta:
        model = models.Verb
        exclude = ('origin',)
        autocomplete_fields = ('owner',)
    
    names = forms.CharField()
    code = forms.CharField(widget=widgets.HiddenInput)
    
    def clean_owner(self):
        value = self.cleaned_data['owner']
        return value.id if value else None
    
    def _post_clean(self):
        pass
    
    def save(self, force_insert=False, force_update=False, commit=True):
        tasks.modifyverb.delay(
            user_id        = request.user.avatar.id,
            object        = self.instance.origin.id,
            verb_id        = self.instance.id,
            names        = form.cleaned_data['names'],
            code        = form.cleaned_data['code'],
            ability        = form.cleaned_data['ability'],
            method        = form.cleaned_data['method'],
            owner        = request.POST['owner'],
        ).get(timeout=5)
        return self

class AccessForm(forms.ModelForm):
    class Meta:
        model = models.Access
        exclude = ()
        autocomplete_fields = ('accessor',)

antioch/plugins/editors/views.py
import json

from django import template, shortcuts, http
from django.conf import settings
from django.views.generic import UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.forms.models import modelformset_factory

from antioch.core import models
from antioch.plugins.editors import tasks, forms

SUCCESS_JSON = '{"msg":"Successful update."}'
EXCEPTION_JSON = '{"msg":"%s"}'

def get_errors_json(form):
    return json.dumps(dict(
        errors = form.errors,
        non_field_errors = form.non_field_errors
    ))

class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs) 

class AjaxFormMixin(object):
    def form_valid(self, form):
        try:
            form.save()
            return http.HttpResponse(SUCCESS_JSON, content_type="application/json")
        except Exception as e:
            return http.HttpResponse(EXCEPTION_JSON % e, content_type="application/json", status=500)
    
    def form_invalid(self, form):
        return http.HttpResponse(get_errors_json(form.errors), content_type="application/json", status=422)

class EditorFormView(LoginRequiredMixin, AjaxFormMixin, UpdateView):
    def get_form_kwargs(self):
        kwargs = super(EditorFormView, self).get_form_kwargs()
        kwargs['user_id'] = self.request.user.avatar.id
        return kwargs
    
class ObjectEditorFormView(EditorFormView):
    template_name = 'object-editor.html'
    form_class = forms.ObjectForm
    model = models.Object
    
class PropertyEditorFormView(EditorFormView):
    template_name = 'property-editor.html'
    form_class = forms.PropertyForm
    model = models.Property
    
class VerbEditorFormView(EditorFormView):
    template_name = 'verb-editor.html'
    form_class = forms.VerbForm
    model = models.Verb

class AccessEditorFormView(LoginRequiredMixin, AjaxFormMixin, UpdateView):
    template_name = 'access-editor.html'
    form_class = modelformset_factory(models.Access, extra=0, form=forms.AccessForm)
    model = models.Access
    
    def get_form_kwargs(self):
        kwargs = dict()
        kwargs['queryset'] = self.model.objects.filter(**{'%s__pk' % self.kwargs['type']: self.kwargs['pk']})
        return kwargs

@login_required
def access_editor(request, type, pk):
    if type not in ('verb', 'property', 'object'):
        raise http.Http404()
    
    Model = getattr(models, type.capitalize())
    m = Model.objects.get(pk=pk)
    
    if(request.method == 'POST'):
        print(request.POST)
        acl = []
        for key in request.POST:
            if not key.startswith('accessid-'):
                continue
            access_id = request.POST[key]
            acl.append(dict(
                access_id    = int(access_id),
                deleted        = bool(int(request.POST['deleted-%s' % access_id])),
                rule        = request.POST['rule-%s' % access_id],
                access        = request.POST['access-%s' % access_id],
                accessor    = request.POST['accessor-%s' % access_id],
                permission    = request.POST['permission-%s' % access_id],
                weight        = int(request.POST['weight-%s' % access_id]),
            ))
        
        tasks.modifyaccess.delay(
            user_id        = request.user.avatar.id,
            object_id    = str(model.id),
            type        = type,
            access        = acl,
        ).get(timeout=5)
    
    return shortcuts.render(request, 'access-editor.html', dict(
        title           = "access editor",
        model           = m,
    ))

antioch/plugins/editors/templates/access-editor.html
{% extends 'trivial.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block header %}
<link rel="stylesheet" href="{% static 'common/css/libs/jquery.ui.theme.css' %}" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet/less" type="text/css" href="{% static 'less/access-editor.less' %}" />
<script type="text/javascript">
$(document).ready(function(){
  less.sheets.push($('link[href="{% static 'less/access-editor.less' %}"]')[0]);
  less.refresh();
});
</script>
{% endblock %}

{% block content %}
<div class="access editor">
  <form id="access-form" method="POST" action="">
    {% csrf_token %}
    <div class="row">
      <div class="col-xs-12">
        <button class="btn" id="add-button"><span class="icon-plus-sign"></span> add rule</button>
      </div>
    </div>
    <div class="row access-rules">
      {% for subform in form %}
      <div id="access-{{ subform.instance.id }}" class="form-inline access-rule">
        <div class="drag-thumb"></div>
        <button type="button" class="btn rule-toggle allow">allow</button>
        <button type="button" class="btn access-toggle group">group</button>
        {{ subform.accessor|add_class:"accessor-field"|add_class:"form-control" }}
        {{ subform.group|add_class:"group-field"|add_class:"form-control" }}
        {{ subform.permission|add_class:"permission-field"|add_class:"form-control" }}
        <button type="button" class="btn delete-rule"><span class="glyphicon glyphicon-trash"></span></button>
      </div>
      {% endfor %}
    </div>
    <div class="fixed-footer row">
      <div class="col-xs-12">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block footer %}
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript" src="{% static 'js/access-editor.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(document).antioch();
    
  var intervalId = setInterval(function(){
    if(!jQuery.ui){
      return;
    }
      $('.access-rules').sortable({
          handle:    ".drag-thumb",
          items:     ".access-rule",  
      });
    clearInterval(intervalId);
  }, 100)
    $('#add-button').click(function(){
        addRule({
            access_id    : 0,
            access        : "group",
            accessor    : "",
            rule        : "allow",
            permission    : "anything",
        });
    });

    {% for access in model.acl.all %}
  // addRule({access_id: {{ access.id }}, rule: "{{ access.rule }}", access: "{{ access.type }}", accessor: "{% if access.type == 'accessor' %}{{ access.accessor }}{% else %}{{ access.group }}{% endif %}", permission: "{{ access.permission }}", weight: {{ access.weight }}});
    {% endfor %}
    
    $('#access-form').submit(saveAccess);
});
</script>
{% endblock %}

antioch/plugins/editors/templates/object-editor.html
{% extends 'trivial.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block header %}
{# {% include 'common/autocomplete_light/static.html' %} #}
<link rel="stylesheet/less" type="text/css" href="{% static 'less/object-editor.less' %}" />
<script type="text/javascript">
$(document).ready(function(){
  less.sheets.push($('link[href="{% static 'less/object-editor.less' %}"]')[0]);
  less.refresh();
});
</script>
{% endblock %}

{% block content %}

<div class="object editor row">
  <form id="object-form" method="POST" action="{{ request.path }}">
      {% csrf_token %}
        {{ form.errors }}
        <div class="col-xs-6">
            <div class="form-group row">
        <div class="col-xs-8">
                <label class="control-label" id="name-label" for="id_name">name:</label>
                {{ form.name|add_class:"form-control"  }}
        </div>
        <div class="col-xs-4">
                <label class="control-label" id="access-label" for="access-button">&nbsp;</label><br>
          <button type="button" class="btn block" id="access-button">access...</button>
              </div>
            </div>
            <div class="form-group">
            <label class="control-label" id="parent-label" for="id_parents_text">parents:</label>
            {{ form.parents|add_class:"form-control"  }}
            </div>
            <div class="form-group">
            <label class="control-label" id="location-label" for="id_location_text">location:</label>
            {{ form.location|add_class:"form-control"  }}
            </div>
            <div class="form-group">
            <label class="control-label" id="owner-label" for="id_owner_text">owner:</label>
            {{ form.owner|add_class:"form-control"  }}
            </div>
        </div>
    
        <div class="attributes col-xs-6 row">
            <div class="verbs col-xs-6">
                <label id="verbs-label" for="verbs-select">verbs:</label>
                <select id="verbs-select" size="2" class="form-control">
                    {% for verb in form.instance.verbs.all %}
                    <option value="{{ verb.id }}">{{ verb.annotated }}</option>
                    {% endfor %}
                </select>
        <div class="btn-group">
                  <button type="button" class="btn btn-default" id="add-verb"><span class="glyphicon glyphicon-plus"></span></button>
                  <button type="button" class="btn btn-default" id="remove-verb"><span class="glyphicon glyphicon-minus"></span></button>
        </div>
            </div>
            <div class="properties col-xs-6">
                <label id="properties-label" for="properties-select">properties:</label>
                <select id="properties-select" size="2" class="form-control">
                    {% for property in form.instance.properties.all %}
                    <option value="{{ property.id }}">{{ property.name }}</option>
                    {% endfor %}
                </select>
        <div class="btn-group">
                  <button type="button" class="btn btn-default" id="add-prop"><span class="glyphicon glyphicon-plus"></span></button>
                  <button type="button" class="btn btn-default" id="remove-prop"><span class="glyphicon glyphicon-minus"></span></button>
              </div>
            </div>
        </div>
    
    <div class="fixed-footer">
      <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
  </form>
</div>

{% endblock %}

{% block footer %}
<script type="text/javascript">
$(document).ready(function(){
    $(document).antioch();
    
  setupAjaxForm($('#object-form'));
  
    $('#verbs-select').dblclick(function(){
        $(document).antioch('handleMessage', {
            command: 'edit',
            details: {
                id: $('#verbs-select').val(),
                kind: 'verb'
            }
        });
    });
    
    $('#properties-select').dblclick(function(){
        $(document).antioch('handleMessage', {
            command: 'edit',
            details: {
                id: $('#properties-select').val(),
                kind: 'property'
            }
        });
    });
    
    $('#access-button').click(function(){
        $(document).antioch('handleMessage', {
            command: 'edit',
            details: {
                id: {{ form.instance.pk }},
                kind: 'access/object',
            }
        });
    });
});
</script>
{% endblock %}

antioch/plugins/editors/templates/property-editor.html
{% extends 'trivial.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block header %}
{# {% include 'common/autocomplete_light/static.html' %} #}
<link rel="stylesheet/less" type="text/css" href="{% static 'less/property-editor.less' %}" />
<script type="text/javascript">
$(document).ready(function(){
  less.sheets.push($('link[href="{% static 'less/property-editor.less' %}"]')[0]);
  less.refresh();
});
</script>
{% endblock %}

{% block content %}
<div class="property editor">
  <form id="property-form" method="POST" action="{{ request.path }}">
    {% csrf_token %}
    <div class="row">
      {{ form.errors }}
      <div class="form-group col-xs-4">
        <label id="name-label" for="name-field">name:</label>
        {{ form.name|add_class:"form-control" }}
      </div>
      <div class="form-group col-xs-3">
        <label id="owner-label" for="owner-field">owner:</label>
        {{ form.owner|add_class:"form-control" }}
      </div>
      <div class="form-group col-xs-3">
        <label id="type-label" for="type-field">type:</label>
        {{ form.type|add_class:"form-control" }}
      </div>
      <div class="col-xs-2">
        <button type="button" class="btn access" id="access-button">access...</button>
      </div>
    </div>
    <div class="property-editor">
      {{ form.value }}
      <textarea id="value-field"></textarea>
    </div>
    <div class="footer row">
      <div class="col-xs-6 form-inline">
        <label id="html-label" for="html-checkbox"><input type="checkbox" id="html-checkbox" /> html</label>
      </div>
      <div class="col-xs-6">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block footer %}
<script type="text/javascript" src="{% static 'js/vendor/CodeMirror-0.91/js/codemirror.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
  $(document).antioch();
  
  var syntaxStates = {
    'string'  : 'DummyParser', 
    'html'    : 'HTMLMixedParser', 
    'python'  : 'antiochParser', 
    'dynamic' : 'antiochParser',
  };
  
  var editor = new CodeMirror(CodeMirror.replace("value-field"), {
    parserfile: ["parsexml.js", "parsecss.js", "parsejavascript.js", "tokenizejavascript.js",
            "parsehtmlmixed.js", "parseantioch.js", "parsedummy.js"],
    path: "{% static 'js/vendor/CodeMirror-0.91/js/' %}",
    stylesheet: "{% static 'js/vendor/CodeMirror-0.91/css/antiochcolors.css' %}",
    content: $('#id_value').val(),
    textWrapping: false,
    lineNumbers: true,
    indentUnit: 4,
    tabMode: "shift",
    height: null,
    width: null,
    initCallback: function(){
      editor.setParser(syntaxStates[$('#id_type').val()]);
    }
  });

  $('#id_type').change(function(){
    var lang = $('#id_type').val();
    editor.setParser(syntaxStates[lang]);
    if(lang == 'string'){
      // show html check
      $('#html-checkbox').add($('#html-label')).removeAttr("disabled");
    }
    else {
      // hide html check
      $('#html-checkbox').add($('#html-label')).attr("disabled", "disabled");
      $('#html-checkbox').removeAttr('checked');
    }
  });
  
  $('#html-checkbox').change(function(){
    var type = $(this).is(':checked') ? 'html' : 'string';
    editor.setParser(syntaxStates[type]);
  });
  
  $('#property-form').submit(function(){
    $('#id_value').val(editor.getCode());
  });
  setupAjaxForm($('#property-form'));
  
  $('#access-button').click(function(){
    $(document).antioch('handleMessage', {
      command: 'edit',
      details: {
        id: {{ form.instance.pk }},
        kind: 'access/property',
      }
    });
  });
});
</script>
{% endblock %}

antioch/plugins/editors/templates/verb-editor.html
{% extends 'trivial.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block header %}
{# {% include 'common/autocomplete_light/static.html' %} #}
<link rel="stylesheet/less" type="text/css" href="{% static 'less/verb-editor.less' %}" />
<script type="text/javascript">
$(document).ready(function(){
  less.sheets.push($('link[href="{% static 'less/verb-editor.less' %}"]')[0]);
  less.refresh();
});
</script>
{% endblock %}

{% block content %}
<div class="verb editor">
  <form id="verb-form" method="POST" action="">
    {% csrf_token %}
    {{ form.errors }}
    <div class="row">
      <div class="form-group col-xs-6">
        <label id="names-label" for="names-field">names:</label>
        {{ form.names|add_class:"form-control" }}
      </div>
      <div class="form-group col-xs-4">
        <label id="owner-label" for="owner-field">owner:</label>
        {{ form.owner|add_class:"form-control" }}
      </div>
      <div class="col-xs-2">
        <button type="button" class="btn access" id="access-button">access...</button>
      </div>
    </div>
    <div class="code-editor">
      {{ form.code }}
      <textarea id="code-field"></textarea>
    </div>
    <div class="footer row">
      <div class="form-group col-xs-6 form-inline" id="type-radio">
        <div class="checkbox">
          <label>{{ form.ability }} intrinsic ability</label>
        </div>
        <div class="checkbox">
          <label>{{ form.method }} callable as method</label>
        </div>
      </div>
      <div class="col-xs-6">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </form>
</div>

{% endblock %}

{% block footer %}
<script type="text/javascript" src="{% static 'js/vendor/CodeMirror-0.91/js/codemirror.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(document).antioch();
    
    var editor = new CodeMirror(CodeMirror.replace("code-field"), {
        parserfile: ["parseantioch.js", "parsedummy.js"],
        path: "{% static 'js/vendor/CodeMirror-0.91/js/' %}",
        stylesheet: "{% static 'js/vendor/CodeMirror-0.91/css/antiochcolors.css' %}",
        content: $('#id_code').val(),
        textWrapping: false,
        lineNumbers: true,
        indentUnit: 4,
        tabMode: "shift",
        height: null,
        width: null,
        initCallback: function(){
            editor.setParser('antiochParser');
        }
    });

    $('#verb-form').submit(function(){
        $('#id_code').val(editor.getCode());
    });
    
    $('#access-button').click(function(){
        $(document).antioch('handleMessage', {
            command: 'edit',
            details: {
                id: {{ form.instance.pk }},
                kind: 'access/verb',
            }
        });
    });
});
</script>
{% endblock %}